import React, { useState } from 'react';

export default function Methodology() {
  const [open, setOpen] = useState(false);

  return (
    <div className="bb-content-section">
      <button className="bb-expander-btn" onClick={() => setOpen(o => !o)}>
        <span style={{ fontFamily: 'var(--mono)', fontSize: 9, color: 'var(--bb-orange)', letterSpacing: '3px', textTransform: 'uppercase' }}>
          Signal Engine Methodology — Multi-Factor v4
        </span>
        <span className={`bb-expander-ico ${open ? 'open' : ''}`}>▼</span>
      </button>

      {open && (
        <div className="bb-expander-body">
          <h3>Multi-Factor Scoring System</h3>
          <p>Signals are generated by scoring <strong style={{ color: 'var(--bb-orange)' }}>13 independent factors</strong> across 4 categories:</p>

          <table className="bb-table" style={{ marginTop: 8, marginBottom: 12 }}>
            <thead>
              <tr><th>Category</th><th>Indicators</th><th>Max Score</th></tr>
            </thead>
            <tbody>
              <tr><td style={{ color: 'var(--bb-green)' }}>Trend</td><td>EMA200, EMA Stack (20&gt;50&gt;200), Supertrend, PSAR</td><td style={{ color: 'var(--bb-orange)' }}>6</td></tr>
              <tr><td style={{ color: 'var(--bb-cyan)' }}>Momentum</td><td>RSI, MACD, Williams %R</td><td style={{ color: 'var(--bb-orange)' }}>4</td></tr>
              <tr><td style={{ color: 'var(--bb-orange)' }}>Volume / Flow</td><td>CMF, OBV, MFI</td><td style={{ color: 'var(--bb-orange)' }}>3</td></tr>
              <tr><td style={{ color: 'var(--text2)' }}>Volatility</td><td>ADX (gate + contextual)</td><td style={{ color: 'var(--text3)' }}>—</td></tr>
            </tbody>
          </table>

          <h3>Signal Thresholds</h3>
          <table className="bb-table" style={{ marginBottom: 12 }}>
            <thead><tr><th>Signal</th><th>Condition</th></tr></thead>
            <tbody>
              <tr><td><span className="bb-tag bb-tag-bull">STRONG BUY</span></td><td>Bull Score ≥ 9</td></tr>
              <tr><td><span className="bb-tag bb-tag-bull">BUY</span></td><td>Bull Score ≥ 6</td></tr>
              <tr><td><span className="bb-tag bb-tag-bear">STRONG SELL</span></td><td>Bear Score ≥ 9</td></tr>
              <tr><td><span className="bb-tag bb-tag-bear">SELL</span></td><td>Bear Score ≥ 6</td></tr>
              <tr><td><span className="bb-tag bb-tag-neutral">RANGE</span></td><td>2/3 range signals triggered</td></tr>
              <tr><td><span className="bb-tag bb-tag-neutral">WAIT</span></td><td>No majority OR ADX &lt; 18 OR momentum conflict</td></tr>
            </tbody>
          </table>

          <h3>Trade Plan — ATR-Based Levels</h3>
          <ul>
            <li>Stop Loss = Entry ± 1.5× ATR</li>
            <li>Target 1 = Entry ± 2.5× ATR</li>
            <li>Target 2 = Entry ± 4.0× ATR</li>
          </ul>

          <h3>Decision Filters Applied</h3>
          <ul>
            <li>Structure filter: ADX &lt; 18 → WAIT (no reliable trend)</li>
            <li>Range detection: 2/3 range signals → MEAN REVERSION mode</li>
            <li>Pullback detection: downtrend + short-term bullish bounce</li>
            <li>Weak trend downgrade: STRONG BUY/SELL → BUY/SELL when ADX &lt; 20</li>
            <li>Momentum conflict filter: prevents premature entries</li>
          </ul>
        </div>
      )}
    </div>
  );
}
